### ISSUE TITLE
I am using PyMata on ROS(only works with python2), how do I read messages sent by Firmata.sendString()?

### ISSUE THREAD

**Issue by jesualdocc** [MrYsLab/PyMata#41]

**Comment by MrYsLab** [comment]
Those messages are sent asynchronously by Firmata. When received they are printed to the console and are [handled here.](https://github.com/MrYsLab/PyMata/blob/98e777251ff49748d5a09b17b473dc9dd91dec99/PyMata/pymata_command_handler.py#L689)
They are not saved so there is no command to read them.
